/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import cfg.ReadWriteConfigureFile;
import TCPServer.TCPServer_PrivateChat;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.DefaultListModel;

/**
 *
 * @author ACER
 */
public class GUI_Server extends javax.swing.JFrame implements PropertyChangeListener{
    TCPServer_PrivateChat server;
    ReadWriteConfigureFile cfg;
    DefaultListModel<String> model = new DefaultListModel<>();
    /**
     * Creates new form GUI_Server
     */
    public GUI_Server() {
        initComponents();
        cfg = new ReadWriteConfigureFile();
        cfg.loadConfigure();
        getCfg();
        server = new TCPServer_PrivateChat();
        server.addPropertyChangeListener(this);
        
    }
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if(evt.getOldValue().equals("add"))
        {
            model.addElement((String)evt.getNewValue());
        }
        else if(evt.getOldValue().equals("remove"))
        {
            model.removeElement((String)evt.getNewValue());
        }
        else if(evt.getOldValue().equals("removeAll"))
        {
            model.removeAllElements();
        }
    }
    
    private void getCfg()
    {
        Pair<String,Integer> pairPrivateChat = cfg.getServerConfigure(ReadWriteConfigureFile.serverPrivateChat);
        tf_serverPrivateChatHost.setText(pairPrivateChat.getKey());
        tf_portPrivateChat.setText(pairPrivateChat.getValue().toString());
        Pair<String,Integer> pairGroupChat = cfg.getServerConfigure(ReadWriteConfigureFile.serverGroupChat);
        tf_serverGroupChatHost.setText(pairGroupChat.getKey());
        tf_portGroupChat.setText(pairGroupChat.getValue().toString());
        Pair<String,Integer> pairSendFile = cfg.getServerConfigure(ReadWriteConfigureFile.serverSendFile);
        tf_serverSendFileHost.setText(pairSendFile.getKey());
        tf_portSendFile.setText(pairSendFile.getValue().toString());
    }
    private void setCfg(String privateChatHost,String groupChatHost,String sendFileHost,int portPrivate,int portGroup,int portSend)
    {
        if(privateChatHost!=null&&groupChatHost!=null&&sendFileHost!=null&&portPrivate>=0&&portGroup>=0&&portSend>=0)
        {
            cfg.adjustServerConfigure(ReadWriteConfigureFile.serverPrivateChat, privateChatHost, portPrivate);
            cfg.adjustServerConfigure(ReadWriteConfigureFile.serverGroupChat, groupChatHost, portGroup);
            cfg.adjustServerConfigure(ReadWriteConfigureFile.serverSendFile, sendFileHost, portSend);
            cfg.loadConfigure();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_onlineUser = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        tf_portPrivateChat = new javax.swing.JTextField();
        tf_portGroupChat = new javax.swing.JTextField();
        tf_portSendFile = new javax.swing.JTextField();
        tf_serverPrivateChatHost = new javax.swing.JTextField();
        tf_serverGroupChatHost = new javax.swing.JTextField();
        tf_serverSendFileHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        togglebtn_startServer = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_onlineUser.setModel(model);
        list_onlineUser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_onlineUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_onlineUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_onlineUser);

        jLabel1.setText("List User");

        tf_portSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_portSendFileActionPerformed(evt);
            }
        });

        tf_serverPrivateChatHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_serverPrivateChatHostActionPerformed(evt);
            }
        });

        jLabel2.setText("Server Send File");

        jLabel3.setText("Server Private Chat");

        jLabel4.setText("Server Group Chat");

        jLabel5.setText("Port");

        jLabel6.setText("Port");

        jLabel7.setText("Port");

        togglebtn_startServer.setText("Start Server");
        togglebtn_startServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglebtn_startServerActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(togglebtn_startServer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_serverGroupChatHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_serverPrivateChatHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_serverSendFileHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_portPrivateChat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_portGroupChat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_portSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_portPrivateChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_serverPrivateChatHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tf_serverGroupChatHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_portGroupChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_serverSendFileHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_portSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(togglebtn_startServer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_serverPrivateChatHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_serverPrivateChatHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_serverPrivateChatHostActionPerformed

    private void tf_portSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_portSendFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_portSendFileActionPerformed

    private void togglebtn_startServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglebtn_startServerActionPerformed
        // TODO add your handling code here:
        if(togglebtn_startServer.isSelected())
        {
            togglebtn_startServer.setText("Stop Server");
            togglebtn_startServer.setBackground(Color.RED);
            Thread thread = new Thread(() -> {
                server.start();
            });
            thread.start();
            
        }
        else{
            togglebtn_startServer.setText("Start Server");
            togglebtn_startServer.setBackground(null);
            try {
                server.stop();
            } catch (IOException ex) {
                Logger.getLogger(GUI_Server.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_togglebtn_startServerActionPerformed

    private void list_onlineUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_onlineUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_list_onlineUserMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setCfg(tf_serverPrivateChatHost.getText(), tf_serverGroupChatHost.getText(), tf_serverSendFileHost.getText(), 
                Integer.parseInt(tf_portPrivateChat.getText()),Integer.parseInt(tf_portGroupChat.getText()) , Integer.parseInt(tf_portSendFile.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> list_onlineUser;
    private javax.swing.JTextField tf_portGroupChat;
    private javax.swing.JTextField tf_portPrivateChat;
    private javax.swing.JTextField tf_portSendFile;
    private javax.swing.JTextField tf_serverGroupChatHost;
    private javax.swing.JTextField tf_serverPrivateChatHost;
    private javax.swing.JTextField tf_serverSendFileHost;
    private javax.swing.JToggleButton togglebtn_startServer;
    // End of variables declaration//GEN-END:variables

    
}
